KitcoBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.KitcoBucket.name}

KitcoBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref KitcoBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:ListBucket
          Resource: arn:aws:s3:::${self:custom.KitcoBucket.name}